# Locations in music21 and Python dictionaries
In this notebook we will expand our konwledge of both music21 and Python. Regarding music21, we will pay special attention to locating objects in their containing streams, but we will also have a look to how music21 handles lyrics and ties. Regarding Python, we will learn about a very powerful class, the dictionaries, which will help us organize information with a greater degree of efficiency.

In this notebook, we will continue working with the score `lsxp-WoBenShi-KongChengJi.xml`. So let's load it. And since we are going to work with the music of the parts in this score, let's save each part in a corresponding variable.

In [1]:
from music21 import *

In [2]:
# Path of the folder that contains the score to be loaded
path = './lsxp-WoBenShi-KongChengJi/'

# Name of the score
file_name = 'lsxp-WoBenShi-KongChengJi.xml'

# Join the path of the folder with the file name to get the full path
fn = path + file_name

# Load the score
s = converter.parse(fn)

# Retrieve parts
p_instr = s.parts[0] # instrumental part
p_vocal = s.parts[1] # vocal part

## Locations in music21
The key concept for locating objects in music21 streams is `offset`. To have an explanation about this concept, please watch [the "Basic concepts in music21" section of the introductory video to music21](https://youtu.be/wrREb68FwNM?t=4764). We already had a glimpse of offsets when we retrieved measures from a part. Let's do this again for the vocal part: retrieve all the measures and just print them out.

In [3]:
mm_vocal = p_vocal.getElementsByClass('Measure').stream()

for m in mm_vocal.elements:
    print(m)

<music21.stream.Measure 0 offset=0.0>
<music21.stream.Measure 1 offset=2.0>
<music21.stream.Measure 2 offset=6.0>
<music21.stream.Measure 3 offset=10.0>
<music21.stream.Measure 4 offset=14.0>
<music21.stream.Measure 5 offset=18.0>
<music21.stream.Measure 6 offset=22.0>
<music21.stream.Measure 7 offset=26.0>
<music21.stream.Measure 8 offset=30.0>
<music21.stream.Measure 9 offset=34.0>
<music21.stream.Measure 10 offset=38.0>
<music21.stream.Measure 11 offset=42.0>
<music21.stream.Measure 12 offset=46.0>
<music21.stream.Measure 13 offset=50.0>
<music21.stream.Measure 14 offset=54.0>
<music21.stream.Measure 15 offset=58.0>
<music21.stream.Measure 16 offset=62.0>
<music21.stream.Measure 17 offset=66.0>
<music21.stream.Measure 18 offset=70.0>
<music21.stream.Measure 19 offset=74.0>
<music21.stream.Measure 20 offset=78.0>
<music21.stream.Measure 21 offset=82.0>
<music21.stream.Measure 22 offset=86.0>
<music21.stream.Measure 23 offset=90.0>
<music21.stream.Measure 24 offset=94.0>
<music21.stre

As you see, in music21 measure streams have both a number and an offset. To retrieve this information, we can conveniently call the attributes `.number` and `.offset` on a measure stream.

Let's take, for example, measure number 10. We can retrieve it by calling the method `.measure()` on the variable where we stored the vocal part, and passing the number `10` as parameter. Then, we will call the attributes `.number` and `.offset` on the variable where we saved the retrieved measure.

In [4]:
m_vocal_10 = mm_vocal.measure(10)

print("Measure number {} of the vocal part starts at offset {}.".format(m_vocal_10.number, m_vocal_10.offset))

Measure number 10 of the vocal part starts at offset 38.0.


Let's now see what this measure contains.

In [5]:
for e in m_vocal_10.elements:
    print(e)

<music21.note.Note E>
<music21.note.Note C#>
<music21.note.Note F#>
<music21.note.Note E>
<music21.note.Note F#>
<music21.note.Note G#>
<music21.note.Note B>
<music21.note.Note G#>
<music21.note.Note F#>
<music21.note.Note E>


Measure 10 only contains notes. And these notes are contained within this measure in specific offsets. We can retrieve the offset of each note by calling the `.offset` attribute on each note.

In [6]:
for n in m_vocal_10.notes.stream():
    print("The note {} starts at offset {}.".format(n.nameWithOctave, n.offset))

The note E4 starts at offset 0.0.
The note C#4 starts at offset 0.25.
The note F#4 starts at offset 0.75.
The note E4 starts at offset 1.0.
The note F#4 starts at offset 1.5.
The note G#4 starts at offset 2.0.
The note B4 starts at offset 2.0.
The note G#4 starts at offset 2.0.
The note F#4 starts at offset 3.0.
The note E4 starts at offset 3.5.


Notice that the offsets of the notes are related to their position within the measure stream that contains them.

Let's now have a look to the offsets of the elements contained in the first measure of the score, which, in this case, has the number `0` because it is an anacrusis.

In [7]:
# Retrieve the measure with the method .measure()
m_vocal_0 = mm_vocal.measure(0)

# Iterate over the elements of the measure
for e in m_vocal_0.elements:
    print("At offset {} there is a {}.".format(e.offset, e))

At offset 0.0 there is a <music21.clef.TrebleClef>.
At offset 0.0 there is a <music21.key.KeySignature of 4 sharps>.
At offset 0.0 there is a <music21.meter.TimeSignature 4/4>.
At offset 0.0 there is a <music21.layout.SystemLayout>.
At offset 0.0 there is a <music21.layout.StaffLayout distance 65, staffNumber 1, staffSize None, staffLines None>.
At offset 0.0 there is a <music21.note.Rest rest>.


As you can see, this measure contains many elements, but none of them is a note. However, all of them are contained in the measure stream in a specific offset, the first one of the measure, and therefore, we can call the `.offset` method on them.

However, we will probably won't want to work measure by measure. Instead, we will probably like to retrieve all notes from a part using the `.notes` attribute, applied to the "flattened" part. Let's retrieve all the notes from the vocal part, and, to be sure that we did it correctly, let's open them in our score editor.

In [8]:
nn_vocal = p_vocal.flat.notes.stream()

nn_vocal.show()

Now that we have all the notes of the vocal part in the stream stored in variable `nn_vocal`, let's retrieve there the notes from measure number 10, which, in `nn_vocal`, are the notes from indexes 10 to 19. To verify that these are the notes we want, let's print them out, and also show them in our score editor.

In [9]:
nn_vocal_m10 = nn_vocal[10:20]

for n in nn_vocal_m10:
    print(n)

nn_vocal_m10.show()

<music21.note.Note E>
<music21.note.Note C#>
<music21.note.Note F#>
<music21.note.Note E>
<music21.note.Note F#>
<music21.note.Note G#>
<music21.note.Note B>
<music21.note.Note G#>
<music21.note.Note F#>
<music21.note.Note E>


If you showed those notes in your score editor, you will have noticed that the score editor creates few empty measures before. Why is this? Well, it has to do with the note offsets. So let's check them:

In [10]:
for n in nn_vocal_m10:
    print("The note {} starts at offset {}.".format(n.nameWithOctave, n.offset))

The note E4 starts at offset 38.0.
The note C#4 starts at offset 38.25.
The note F#4 starts at offset 38.75.
The note E4 starts at offset 39.0.
The note F#4 starts at offset 39.5.
The note G#4 starts at offset 40.0.
The note B4 starts at offset 40.0.
The note G#4 starts at offset 40.0.
The note F#4 starts at offset 41.0.
The note E4 starts at offset 41.5.


As you can see, the first note starts at offset `38.0`, so the score editor, having this information, has to leave the space equivalent to 38 quarter notes free before the first note. But, why, if these are the same notes that we analysed before, the offset is now different? Because their container is also different. Previously, we retrieved these notes from their measure, so the offsets were related to that measure. However, now we are retrieving these notes from a stream that we created and saved in the variable `nn_vocal`, and this stream is created by "flattening" the vocal part saved in the variable `p_vocal`. Therefore, the offsets of the notes contained in `nn_vocal` are no longer related to the measures where they were originally contained, but to the entire part.

However, having the notes in this new stream doesn't mean that we lost the measure information. We can still retrieve this information by calling the `.measure` attribute on a note. Besides, we can even know in which beat of the measure a note starts, by calling the `.beat` attribute. Let's retrieve the measure and beat information from the notes of measure 10 that we saved in the variable `nn_vocal_m10`.

In [11]:
for n in nn_vocal_m10:
    print("The note {} is in measure {}, beat {}.".format(n.nameWithOctave, n.measureNumber, n.beat))

The note E4 is in measure 10, beat 1.0.
The note C#4 is in measure 10, beat 1.25.
The note F#4 is in measure 10, beat 1.75.
The note E4 is in measure 10, beat 2.0.
The note F#4 is in measure 10, beat 2.5.
The note G#4 is in measure 10, beat 3.0.
The note B4 is in measure 10, beat 3.0.
The note G#4 is in measure 10, beat 3.0.
The note F#4 is in measure 10, beat 4.0.
The note E4 is in measure 10, beat 4.5.


As we saw previously, everything that is contained in a measure is located in a specific position, which is indicated by an offset, but also by a beat. Therefore, all the objects contained in the first measure of the part also have measure and beat information. Let's call the `.measure` and `.beat` attributes on the objects of the first measure.

In [12]:
for e in m_vocal_0.elements:
    print("The element {} is in measure {}, beat {}.".format(e, e.measureNumber, e.beat))

The element <music21.clef.TrebleClef> is in measure 0, beat 3.0.
The element <music21.key.KeySignature of 4 sharps> is in measure 0, beat 3.0.
The element <music21.meter.TimeSignature 4/4> is in measure 0, beat 3.0.
The element <music21.layout.SystemLayout> is in measure 0, beat 3.0.
The element <music21.layout.StaffLayout distance 65, staffNumber 1, staffSize None, staffLines None> is in measure 0, beat 3.0.
The element <music21.note.Rest rest> is in measure 0, beat 3.0.


As you can see, clefs, key signatures, time signatures and other objects also have information about the measure where they are contained, and in which specific beat.

By the way, notice that all these objects in this anacrusis measure, which, remember, are all located at offset `0.0`, are stored in beat `3.0`. This shows that music21 is aware that this first measure is an anacrusis measure, with a time signature of 4/4, in which the first two beats are missing. Great!

So, as we just saw, we can retrieve information from this non-note objects. So let's look a bit more in depth on that. First, let's focus on key signature. And first of all, let's retrieve all the key signatures present in the vocal part by calling the `.getElementsByClass()` method on the "flattened" part. And remember, music21 likes you to keep your retrieved objects in streams.

⇒ **Note**: since key signatures are stored within measures, if do not use the `.flat` attribute we could only retrieve key signature objects from a measure stream. So, if we want to retrieve all the key signatures from a part, we need to use the `.flat` attribute.

In [13]:
kss = p_vocal.flat.getElementsByClass('KeySignature').stream()

print('The vocal part contains {} key signatures.'.format(len(kss)))

The vocal part contains 1 key signatures.


The vocal part of this score only contains 1 key signature. So, let's save it into a variable to better work with it.

In [14]:
ks = kss[0]

print(ks)

<music21.key.KeySignature of 4 sharps>


So now that we have the key signature saved in the variable `ks`, the next cell shows some of the information that can be retrieved from it. Pay attention to all the different attributes.

In [15]:
print('Offset:', ks.offset)
print('Measure number:', ks.measureNumber)
print('Beat:', ks.beat)
print('Number of altered pitches:', ks.sharps)
print('List of altered pitches:')
for p in ks.alteredPitches:    # the attribute .alteredPitches retrieves a list of pitches
    print('-', p.name)
print('Major key:', ks.asKey('major'))
print('Major key:', ks.asKey('minor'))
print('Minor key:', ks.asKey('dorian'))

Offset: 0.0
Measure number: 0
Beat: 3.0
Number of altered pitches: 4
List of altered pitches:
- F#
- C#
- G#
- D#
Major key: E major
Major key: c# minor
Minor key: F# dorian


Let's do now the same with time signatures. First, we retrieve all the time signatures in the part.

In [16]:
tss = p_vocal.flat.getElementsByClass('TimeSignature').stream()

print('The vocal part contains {} time sigantures.'.format(len(tss)))

The vocal part contains 2 time sigantures.


In this case, this score has two time signatures. This might be useful to know for our analysis. Luckily, even though we retrived them from the "flattened" part, we still can know in which measure, and even beat, each time signature is located.

In [17]:
print('The first time signature is in offset {}, measure {}, beat {}.'.format(tss[0].offset, tss[0].measureNumber, tss[0].beat))
print('The second time signature is in offset {}, measure {}, beat {}.'.format(tss[1].offset, tss[1].measureNumber, tss[1].beat))

The first time signature is in offset 0.0, measure 0, beat 3.0.
The second time signature is in offset 530.0, measure 133, beat 1.0.


The most relevant information we can retrieve from a time signature is the number of beats per measure and the duration value for each beat. The former can be known from the `.numerator` of the time signature, and the latter from its `.denominator`, if we take the time signature as a fraction.

In [18]:
print('The first time signature is a {}/{}.'.format(tss[0].numerator, tss[0].denominator))
print('The second time signature is a {}/{}.'.format(tss[1].numerator, tss[1].denominator))

The first time signature is a 4/4.
The second time signature is a 2/4.


⇒ **Note**: Of course, much more information than this can be retrieved from a time signature. If you want to explore it, save one time signature in a variable and run the cell. Then write the name of the variable followed by a period and press the tabulator. A pop-up window will appear with all the options. You can select one and write a question mark `?` directly after it. A new window will apppear with the docstrings of that attribute or method.

Finally, let's do the same for the clefs. First, we retrieve them.

In [19]:
clefs = p_vocal.flat.getElementsByClass('Clef').stream()

print('The vocal part contains {} clef.'.format(len(clefs)))

The vocal part contains 1 clef.


To better work with the only clef of the score, we save it first in a variable. Pay attention to the attributes called in the next cell.

In [20]:
clef = clefs[0]

print('Offset:', clef.offset)
print('Measure number:', clef.measureNumber)
print('Beat:', clef.beat)
print('Name:', clef.name)
print('Sing:', clef.sign)
print('Line:', clef.line)

Offset: 0.0
Measure number: 0
Beat: 3.0
Name: treble
Sing: G
Line: 2


## Lyrics and ties
Before moving on to Python dictionaries, let's briefly look at two important elements in a score: lyrics and ties.

### Lyrics
Lyrics are specific objects in music21, and as `pitch` and `duration` objects, they are contained in the `note` objects. So, to explore lyrics, let's take the first note of measure 10 and save it in a variable.

In [21]:
n_m10_0 = nn_vocal_m10[0]

We can acces the lyrics of this note by calling the attribute `.lyrics`.

In [22]:
ll = n_m10_0.lyrics

print(ll)

[<music21.note.Lyric number=1 syllabic=single text="卧">]


Notice that what the `.lyrics` attribute retrieves is a list, as indicated by the square brackets `[ ]`. Why would a note contain a list of lyrics? This is thought for scores of melodies sung with different lyrics, as it is the case of many folk songs. In this cases, the score gives the different stanzas of lyrics to one line of notation. As a result, one note can have more than one line of lyrics.

The retrieved list from the cell above contains only one lyric object. This object has three attributes. `number` indicates the number of the line, for those notes with more than one line of lyrics. `syllabic` indicates the position of the syllable contained in that note with the word to which it belongs. If we sing the word "Despacito", we will sing each syllable with one note. So, in the note containing the lyric "Des-", the value of `syllabic` will be `begin`. In the note with the lyric "-to", the value of `syllabic` will be `end`. And for "-pa-" and "-ci-" the value of `syllabic` will be `middle`. In the case of monosyllabic words, as it is the case for all Chinese characters, the `syllabic` value is `single`. And finally, `text` indicates the specific string of that particular lyric.

We can access each item of information by calling the corresponding attribute on the lyric object. So let's save it first in a variable, and then call all these three attributes.

In [23]:
l = ll[0]

print('Text:', l.text)
print('Line:', l.number)
print('Syllabe with respect to word:', l.syllabic)

Text: 卧
Line: 1
Syllabe with respect to word: single


However, most of the time, we will be just interested in the string of lyric. So we can retrieve it directly from the note with the attribute `.lyric`.

In [24]:
print('The first note of measure 10 in the vocal part hast the lyric {}.'.format(n_m10_0.lyric))

The first note of measure 10 in the vocal part hast the lyric 卧.


⇒ **Note**: in the case that a note have different lines of lyrics, the `.lyric` method will return all the lyrics from different lines in a single string, separated by the new line escape sequence (`\n`).

So, now that we know how to retrieve the lyrics from notes, let's print all the lyrics of the notes from measure 10. Remember that we stored them in variable `nn_vocal_m10`.

In [25]:
for n in nn_vocal_m10:
    print(n.lyric)

卧
None
None
龙
None
None
None
岗
None
None


Well, not all notes have lyrics. So, maybe we could check if a note has a lyric before trying to print it out.

In [26]:
# Iterate over the notes
for n in nn_vocal_m10:
    # Check if the value of the .lyric attribute is different from None
    if n.lyric != None:
        print(n.lyric)

卧
龙
岗


### Ties
The duration object gives us information about how long a note is performed. However, what happens when two notes are tied? Note objects in music21 contain an attribute called `.tie` that contains the information about the note being tied or not.

In our score, the last two notes of the vocal part are tied. So, let's save them in one variable each to better work with them. And just to compare them with not tied notes, let's also save the antepenultimate note in a variable.

In [27]:
nx = nn_vocal[-3]
ny = nn_vocal[-2]
nz = nn_vocal[-1]

# Print pitch and duration names to verify that we accessed the right notes
print('The antepenultimate note is a {} {} note.'.format(nx.nameWithOctave, nx.duration.fullName))
print('The penultimate note is a {} {} note.'.format(ny.nameWithOctave, ny.duration.fullName))
print('The last note is a {} {} note.'.format(nz.nameWithOctave, nz.duration.fullName))

The antepenultimate note is a C#4 16th note.
The penultimate note is a E4 Quarter note.
The last note is a E4 Eighth note.


So, to check if a note is part of a tie, we can call the attribute `.tie` on it. If it is NOT part of a tie, the value of this attribute will be `None`.

In [28]:
print('Is the antepenultimate note part of a tie?', nx.tie != None)
print('Is the penultimate note part of a tie?', ny.tie != None)
print('Is the last note part of a tie?', nz.tie != None)

Is the antepenultimate note part of a tie? False
Is the penultimate note part of a tie? True
Is the last note part of a tie? True


So now that we have verified that the penultimate and last notes are part of a tie, we can even know in which part of the tie they are, either the `start` or the `stop`.

In [29]:
print('The antepenultimate note is {} of a tie.'.format(ny.tie.type))
print('The last note is {} of a tie.'.format(nz.tie.type))

The antepenultimate note is start of a tie.
The last note is stop of a tie.


⇒ **Note**: if more than two notes are tied, the value fo the `.tie.type` attribute for the notes in the middle will be `continue`.

## Python dictionaries
So far, we have been storing our collections of data in lists. However, Python has a more powerful way for storing data: dictionaries.

Each item of data stored in a dictionary contains two elements, a `key` and a `value`. We will see in the next cell what is the meaning of this, but for the moment, let's just look at the format of a dictionary. If lits are indicated by square brackets (`[ ]`), dictionaries are defined by curly brackets (`{ }`). Then each item within the dictionary is separated by commas (`,`). And the two elements of each item, that is, the `key` and the `value` are separated by colon (`:`). The `key` always comes firts.

Let's see an example. We will create a dictionary that contains personal information about a person, and we will assign it to a variable, `person_01`. We will add that information as `value`s, and we will "label" them with a corresponding `key`. To check which type of object is saved in the variable `person_01`, we will print the output of the `type()` function.

In [30]:
person_01 = {'name': 'John Smith', 'age': 35, 'height': 1.78, 'married': False}

print(type(person_01))

<class 'dict'>


As you can see, we created a dictionary using the curly brackets, and we saved it in the variable `person_01`.

The dictionary contains four items:

1. In the first one, the `key` is `'name'` and the `value` is `'John Smith'`.
2. In the second one, the `key` is `'age'` and the `value` is `35`.
3. In the third one, the `key` is `'height'` and the `value` is `1.78`.
4. In the fourth one, the `key` is `'married'` and the `value` is `False`.

If we print the type of data that is contained in the variable `person_01`, we get indeed a `dict` (short form of `dictionary`).

To understand the benefits of a dictionary, let's compare it with a list. We could have all the information about this person stored in a list in this way:

    person_01 = ['John Smith', 35, 1.78, False]
    
So, if we want to retrieve any particular item of information, we will need to remember its index. However, with a dictionary, each item of information is "labeled" with a `key`, and we can retrieve that information, that is, that `value`, by calling its corresponding `key`. Let's retrieve, for example, this person's height.

In [31]:
person_01['height']

1.78

In the previous cell, we retrieved the information about height by calling the `key` `'height'` within square brackets right next to the name of the variable in which we saved the dictionary. The format looks very similar to indexing. But with dictionaries, we don't need to remeber the index of each item of information. We can conveniently call the `key` instead.

In fact, dictionaries do not accept indexing. If we try to retrieve the same information using the index `2` we will get an error:

In [32]:
person_01[2]

KeyError: 2

If you noticed, the type of error we got is a `KeyError`. This means that the code didn't consider `2` as an index, but as a `key`. Since the variable `person_01` contains a dictionary, if we use square brackets after it, Python understands that we are calling a `key`, not an index.

By the way, pay attention to the types of data of the values of our dictionary. The first `value` (`'John Smith'`) is a string. The second (`35`) is an integer. The third (`1.78`) is a floating point and the fourth (`False`) is a boolean. Dictionary values can be of any sort of data type. Regarding keys, in our dictionary all of them are strings, but actually, they can be of any type. For example, here's a dictionary in which the keys are integers:

In [33]:
students_per_year = {2015: 23, 2016: 25, 2017: 21, 2018: 21, 2019: 21}
print(students_per_year)

{2015: 23, 2016: 25, 2017: 21, 2018: 21, 2019: 21}


⇒ **Note**: even though in the dictionary saved in the variable `person_01` and in the one in `students_per_year` all the keys are of the same data type, this does not necessarily have to be so. Keys of one dictionary can be of different data types.

⇒ **Note**: a dictionary can have items of information with identical values, as you can see in the previous dictionary with the values of the keys `2017`, `2018` and `2019`. However, keys cannot be repeated, they have to be unique. And this makes logical sense: if a dictionary contains two identical keys, how would Python know to which one you are referring to when you call any of those?

The information of this second dictionary can be retrieved in the same way as in the first one:

In [34]:
print('How many students were there in 2018?')
print(students_per_year[2018])

How many students were there in 2018?
21


So, let's use all the information stored in the first dictionary:

In [35]:
print('The first person is called {}.'.format(person_01['name']))
print('He is {} years old.'.format(person_01['age']))
print('He is {} metres tall.'.format(person_01['height']))
# Since the value of the key 'married' is a boolean, let's print a specific message accordingly
if person_01['married']:
    print('He is married.')
else:
    print('He is not married.')

The first person is called John Smith.
He is 35 years old.
He is 1.78 metres tall.
He is not married.


The `value` of a specific `key` can be modified, or, better said, re-defined by using the operator `=`:

In [36]:
person_01['married'] = True

# Same code as in the previous cell
if person_01['married']:
    print('He is married.')
else:
    print('He is not married.')

He is married.


Now, the `value` of the `key` `'married'` is no longer `False`, but `True`.

In [37]:
print(person_01)

{'name': 'John Smith', 'age': 35, 'height': 1.78, 'married': True}


In fact, we can modify the values of specific keys using all the operators, attributes and methods applicable to the data type of those values. For example, the `value` of the key `age` is an integer. So we can add `2` to that integer using the operator `+=`:

In [38]:
person_01['age'] += 2

print(person_01)

{'name': 'John Smith', 'age': 37, 'height': 1.78, 'married': True}


We can expand our dictionaries by adding new items of information. In order to do that, we call the new `key` in square brackes right after the name of the variable that stores the dictionary, and we assign a `value` to it using the `=` operator.

Let's add the hobbies of this person to our dictionary. For that, we call the new key `'hobbies'` within square brackets on the dictionary saved in the variable `person_01`. That `key` doesn't exists yet in the dictionary, we will create it by assigning a `value` to it using the operator `=`.

Usually, people have more than one hobby. So, since values in a dictionary can be of any data type, let's assign a list to the `key` `'hobbies'` containing all the hobbies of this person.

In [39]:
person_01['hobbies'] = ['painting', 'fencing', 'gardening']

print(person_01)

{'name': 'John Smith', 'age': 37, 'height': 1.78, 'married': True, 'hobbies': ['painting', 'fencing', 'gardening']}


Now, our dictionary contains a new `key`, `'hobbies'`, with a list as `value`.

In [40]:
print(person_01['hobbies'])

['painting', 'fencing', 'gardening']


And we can use it as any other list.

In [41]:
for hobby in person_01['hobbies']:
    print(hobby)

painting
fencing
gardening


As mentioned before, values can be modified using the operators, attributes and methods that are applicable to the data type of those values. Since the `value` of the `key` `'hobbies'` is a list, we can modify it using any of the list methods. For example, let's add a new hobby to the list of hobbies. The way of adding an item to a list is using the `.append()` method. So, let's call this method when calling the `key` `'hobbies'` on the `person_01` dictionary.

In [42]:
person_01['hobbies'].append('knitting')

# Print the new value of the key 'hobbies' to see the changes
print(person_01['hobbies'])

['painting', 'fencing', 'gardening', 'knitting']


Let's now create two new dictionaries for containing information about two new people. However, now we will create these dictionaries starting from an empty one, and we will be adding the `key` and `value` of each item one by one using the `=` operator.

In [43]:
# Dictionary for person_02
## Define empty dictionary
person_02 = {}

## Add information
person_02['name'] = 'Carol Smith'
person_02['age'] = 5
person_02['height'] = 0.95

# Dictionary for person_03
## Define empty dictionary
person_03 = {}

## Add information
person_03['name'] = 'Louise Smith'
person_03['age'] = 2
person_03['height'] = 0.51

# Print the dictionaries
print(person_02)
print(person_03)

{'name': 'Carol Smith', 'age': 5, 'height': 0.95}
{'name': 'Louise Smith', 'age': 2, 'height': 0.51}


Dictionaries can be as complex as you want, since they are very versatile. For example, imagine that the dictionaries we just created correspond to the daughters of the person one. So, we can add that information in the `person_01` dictionary, as a list of containing the `person_02` and `person_03` dictionaries.

In [44]:
person_01['offspring'] = [person_02, person_03]

print(person_01)

{'name': 'John Smith', 'age': 37, 'height': 1.78, 'married': True, 'hobbies': ['painting', 'fencing', 'gardening', 'knitting'], 'offspring': [{'name': 'Carol Smith', 'age': 5, 'height': 0.95}, {'name': 'Louise Smith', 'age': 2, 'height': 0.51}]}


So, the dictionary saved in the variable `person_01` contains an item whose value is list that contains two dictionaries. Wow!

And now we can very conveniently retrieve all the different items of information saved in that dictionary.

In [45]:
print('The first person has {} daughters:'.format(len(person_01['offspring'])))

for daughter in person_01['offspring']:
    print('- {}, {} years old, {} meters high.'.format(daughter['name'], daughter['age'], daughter['height']))

The first person has 2 daughters:
- Carol Smith, 5 years old, 0.95 meters high.
- Louise Smith, 2 years old, 0.51 meters high.


I hope that you started gaining an idea of the potential of dictionaries for storing and organizing information.

Dictionaries, as all Python objects, have their own methods. Arguably the most used ones are the `.keys()` and `.values()` methods. Each of them respectively returns all the keys of a dictionary and all the values of a dictionary.

Let's see first all the keys of our dictionary `person_01`:

In [46]:
print(person_01.keys())

dict_keys(['name', 'age', 'height', 'married', 'hobbies', 'offspring'])


And now, all its values:

In [47]:
print(person_01.values())

dict_values(['John Smith', 37, 1.78, True, ['painting', 'fencing', 'gardening', 'knitting'], [{'name': 'Carol Smith', 'age': 5, 'height': 0.95}, {'name': 'Louise Smith', 'age': 2, 'height': 0.51}]])


Excellent! Dictionaries are great! But, how can they help us in our musicological research?

A common use is gathering information for a series of elements that were unknown *a priory*. For example, in exercise 2.6 from notebook 7 we could count the aggregated duration of all the pitches of the score. However, that code requires that we know beforehand the pitches contained in a score. And then, we need to create a variable for each of them, check for each note if its pitch corresponds to any of those, etc. The result, is a quite lengthy code. With dictionaries we can do the same task much more efficiently, since we can have a dictionary with the pitch classes of the score as keys, and their aggregated duration as values. To do that, we can create an empty dictionary, then iterate over the notes, if the note's pitch is not among the keys in our dictionary, we create it defining the duration of the note as its value, but if it alreay is among the keys, then we update its value by adding the new duration.

Better seen than explained:

In [48]:
# Create empty dictionary
pitch_durations = {}

# Iterate over all notes
for n in nn_vocal:
    # Retrive pitch and duration
    n_pitch = n.name
    n_dur = n.quarterLength
    # Check if pitch is already a key in the dictionary
    if n_pitch not in pitch_durations.keys():
        # Since it is not, we create the key and assign the duration as value
        pitch_durations[n_pitch] = n_dur
    else:
        # Since is already is, we update its value by adding the new duration
        pitch_durations[n_pitch] += n_dur

# Print the dictionary
print(pitch_durations)

{'G#': 48.25, 'B': 39.25, 'F#': 45.75, 'E': 40.75, 'C#': 37.75, 'D#': 12.5, 'A': 3.5}


Besides saving coding space, now we can retrieve detailed information at our convenience. For example, how long is the pitch E peformed?

In [49]:
print('Pitch E is performed for an aggregated duration of {} quarter notes.'.format(pitch_durations['E']))

Pitch E is performed for an aggregated duration of 40.75 quarter notes.


What about the 4th and 7th degrees, in this case, A and D#?

In [50]:
print('Pitch A is performed for an aggregated duration of {} quarter notes.'.format(pitch_durations['A']))
print('Pitch D# is performed for an aggregated duration of {} quarter notes.'.format(pitch_durations['D#']))

Pitch A is performed for an aggregated duration of 3.5 quarter notes.
Pitch D# is performed for an aggregated duration of 12.5 quarter notes.


Or we can even print all the information by iterating over the keys of the dictionary:

In [51]:
for p in pitch_durations.keys():
    print('- {} is sung for {} quarter notes.'.format(p, pitch_durations[p]))

- G# is sung for 48.25 quarter notes.
- B is sung for 39.25 quarter notes.
- F# is sung for 45.75 quarter notes.
- E is sung for 40.75 quarter notes.
- C# is sung for 37.75 quarter notes.
- D# is sung for 12.5 quarter notes.
- A is sung for 3.5 quarter notes.


## Exercises

### Exercise 1. Debugging

### 1.1

In [52]:
followers = {'Facebook': 891, 'Twitter': 1786, 'Instagram': 3207}

# Followers in Instagram
print('I have {} followers in Instagram.'.format(followers['Instagram']))

I have 3207 followers in Instagram.


### 1.2

In [53]:
# This cell uses the variable followers from exercise 1.1

# Add followers in LinkedIn and Academia
followers['LinkedIn'] = 107
followers['Academia'] = 12

# Update Twitter and Instagram followers

followers['Twitter'] += 9
followers['Instagram'] += 38 #I changed the second line from Twitter to Instagram - hopefully that's right?

# Print the updated dictionary
print(followers)
print()

# Print followers in Facebook and LinkedIn
print('I have {} followers in Facebook and {} followers in LinkedIn'.format(followers['Facebook'], followers['LinkedIn']))

{'Facebook': 891, 'Twitter': 1795, 'Instagram': 3245, 'LinkedIn': 107, 'Academia': 12}

I have 891 followers in Facebook and 107 followers in LinkedIn


### 1.3. Reading phone numbers

In [54]:
# Dictionary with numbers and their pronunciation
numbersDict = {0: 'zero', 1: 'one', 2: 'two', 3: 'three', 4: 'four', 5: 'five', 6: 'six', 7: 'seven', 8: 'eight', 9: 'nine'}

# Target phone number
phoneNumber = '667027084'
print('The number you dialed is:')

# Iterate over all the digits of the number
for digit in phoneNumber:
# Retrieve its pronunciation from the dictionary and print it out
    print(numbersDict[int(digit)])

The number you dialed is:
six
six
seven
zero
two
seven
zero
eight
four


### 1.4

In [55]:
# Create an empty dictionary
myWeirdDict = {}

# Add items
myWeirdDict['name'] = 'Hermione'
myWeirdDict[10] = 'ten'
myWeirdDict['cities'] = ['New York', 'Moscow', 'Eggersdorf']
myWeirdDict[2.3] = 'New updated version with several improvements.'
myWeirdDict['Happy?'] = True
myWeirdDict['Injuries'] = None

# Print dictionary
print(myWeirdDict)
print()

# Retrieve your name if you are happy
if myWeirdDict['Happy?'] == True:
    print(myWeirdDict['name'])

print()

# Change the pronunciation of 10 to German and print it out
myWeirdDict[10] = 'Zehn'
print(myWeirdDict[10])

print()

# Add Minas Tirith to the list of cities and print how many cities you have visited
myWeirdDict['cities'].append('Minas Tirith')
print('I have visited {} cities.'.format(len(myWeirdDict['cities'])))

{'name': 'Hermione', 10: 'ten', 'cities': ['New York', 'Moscow', 'Eggersdorf'], 2.3: 'New updated version with several improvements.', 'Happy?': True, 'Injuries': None}

Hermione

Zehn

I have visited 4 cities.


### 1.5. Counting vowels

In [56]:
# Define the counting vowels function
def count_vowels(phrase):
    '''
    Returns a dictionary with the found vowels as keys and the number of occurrences of this vowel as values
    
    Args
        phrase (str): a string whose vowels will be counted
        
    Returns
        vowels_count (dict): a dictionary with the found vowels as kyes and the number of occurrences as values
        
    >>> count_vowels('Hakuna matata!')
    {'a': 5, 'u': 1}
    '''
    
    # All vowels variable
    vowels = 'AEIOUaeiou'
    
    # Create an empty dictionary
    vowels_count = {}
    
    # Iterate over all the letters of phrase
    for letter in phrase:
        # Check if it is a vowel
        if letter in vowels:
            # Check if that letter is NOT yet a key in the dictionary
            if letter not in vowels_count.keys():
                # It is not yet there, so create it with the value of 1
                vowels_count[letter] = 1
            else:
                # It is already there, so update its value by 1
                vowels_count[letter] += 1
    
    return vowels_count

# Phrases to be tested
phrase1 = 'Always look at the bright side of life.'
phrase2 = 'Give me a place to stand, and I shall move the world.'
phrase3 = 'A-bop-bop-a-loom-op a-lop-bop-boom!'

# Calls to the function 
phrase1_vowels = count_vowels(phrase1)
print(phrase1_vowels)
phrase2_vowels = count_vowels(phrase2)
print(phrase2_vowels)
phrase3_vowels = count_vowels(phrase3)
print(phrase3_vowels)

print()

# Results for the vowel 'o'
print('Phrase 1 contains {} oes.'.format(phrase1_vowels['o']))
print('Phrase 2 contains {} oes.'.format(phrase2_vowels['o']))
print('Phrase 3 contains {} oes.'.format(phrase3_vowels['o']))

{'A': 1, 'a': 2, 'o': 3, 'e': 3, 'i': 3}
{'i': 1, 'e': 5, 'a': 5, 'o': 3, 'I': 1}
{'A': 1, 'o': 9, 'a': 2}

Phrase 1 contains 3 oes.
Phrase 2 contains 3 oes.
Phrase 3 contains 9 oes.


⇒ **Challenge**: the function of the last cell counts uppercase and lowercase vowels separately. What could you do to avoid that? *Hint*: strings have a method which returns a lowercase copy of the given string (even if it was already lowercase).

### Exercise 2. Flawed logic

### 2.1
In the exercise 3.5 from notebook 7 we learnt that the highest note in the vocal part is B4. Find all the occurrences of this pitch and print their measure and beat.

Expected result:

    The pitch B4 is reached in the following positions:
    - Measure 8, beat 3.0
    - Measure 8, beat 4.0
    - Measure 9, beat 3.0
    - Measure 10, beat 3.0
    - Measure 13, beat 3.5
    - Measure 24, beat 4.0
    - Measure 26, beat 3.0
    - Measure 37, beat 4.5
    - Measure 40, beat 2.5
    - Measure 70, beat 3.0
    - Measure 75, beat 3.75
    - Measure 87, beat 3.0
    - Measure 88, beat 3.0
    - Measure 90, beat 3.0
    - Measure 90, beat 3.5
    - Measure 100, beat 3.0
    - Measure 106, beat 3.25
    - Measure 106, beat 3.75
    - Measure 118, beat 3.5
    - Measure 119, beat 3.0
    - Measure 119, beat 3.5
    - Measure 152, beat 2.75

In [57]:
# This cell uses the nn_vocal previously defined

print('The pitch B4 is reached in the following positions:')

for n in nn_vocal:
    n_pitch = n.nameWithOctave
    if n_pitch == 'B4':
        print('- Measure {}, beat {}'.format(n.measureNumber, n.beat))

The pitch B4 is reached in the following positions:
- Measure 8, beat 3.0
- Measure 8, beat 4.0
- Measure 9, beat 3.0
- Measure 10, beat 3.0
- Measure 13, beat 3.5
- Measure 24, beat 4.0
- Measure 26, beat 3.0
- Measure 37, beat 4.5
- Measure 40, beat 2.5
- Measure 70, beat 3.0
- Measure 75, beat 3.75
- Measure 87, beat 3.0
- Measure 88, beat 3.0
- Measure 90, beat 3.0
- Measure 90, beat 3.5
- Measure 100, beat 3.0
- Measure 106, beat 3.25
- Measure 106, beat 3.75
- Measure 118, beat 3.5
- Measure 119, beat 3.0
- Measure 119, beat 3.5
- Measure 152, beat 2.75


### 2.2
Let's check how many ties are present in the vocal part.

Expected result:

    The vocal part contains 12 ties.

⇒ **Note**: To avoid counting the same tie for as many times as notes are contained in the tie, search only for notes with tie of the type `start` 

In [59]:
# This cell uses the nn_vocal previously defined

# Ties counter
ties = 0

# Iterate over the notes
for n in nn_vocal:
    # Check if the note has a tie and that it is of type 'start'
    # (to avoid counting the same tie for as many times as notes involved)
    if n.tie and n.tie.type == 'start':
        ties += 1
        
print('The vocal part contains {} ties.'.format(ties))

The vocal part contains 12 ties.


### 2.3
Let's analyze the occurrences of each note duration in the vocal part.

Expected result:

    {'16th': 125, 'Eighth': 161, 'Quarter': 81, 'Dotted Quarter': 3, 'Dotted Eighth': 23, 'Half': 7, 'Whole': 1, 'Dotted Half': 3}

    The vocal part contains 81 quarter notes and 161 eighth notes.

⇒ **Note**: Since we don't know beforehand how many different types of note durations are present in the vocal part, we can start with an empty dictionary. In this dictionary, the keys will be names of the different note durations that we find in the vocal part, and their values the number of occurrences of each type of note duration.

In [62]:
# This cell uses the nn_vocal previously defined

# Create an empty dictionary
durations = {}

# Iterate over all notes
for n in nn_vocal:
    # Retrieve the type of note duration
    nd = n.duration.fullName
    # Check if the duration type of the current note is NOT yet among the keys of the durations dictionary
    if nd not in durations.keys():
        # Add the duration type of the current note as a new key with an initial value of 1
        durations[nd] = 1
    else:
        # The duration type is already among the keys of the durations dictionary
        # Update its value by 1
        durations[nd] += 1

# Print the resulting dictionary
print(durations)

print()

# Retrieve some information
print('The vocal part contains {} quarter notes and {} eighth notes.'.format(durations['Quarter'], durations['Eighth']))

{'16th': 125, 'Eighth': 161, 'Quarter': 81, 'Dotted Quarter': 3, 'Dotted Eighth': 23, 'Half': 7, 'Whole': 1, 'Dotted Half': 3}

The vocal part contains 81 quarter notes and 161 eighth notes.


### 2.4
Let's see which are the preferred beats for singing lyrics.

Expected result:

    {3.0: 35, 4.0: 16, 2.0: 21, 1.0: 31, 3.5: 4, 4.5: 4, 4.75: 1, 2.75: 1, 2.5: 2, 1.5: 3}

    - Beat 1.0: lyrics were sung 31 times
    - Beat 1.5: lyrics were sung 3 times
    - Beat 2.0: lyrics were sung 21 times
    - Beat 2.5: lyrics were sung 2 times
    - Beat 2.75: lyrics were sung 1 times
    - Beat 3.0: lyrics were sung 35 times
    - Beat 3.5: lyrics were sung 4 times
    - Beat 4.0: lyrics were sung 16 times
    - Beat 4.5: lyrics were sung 4 times
    - Beat 4.75: lyrics were sung 1 times

⇒ **Note**: Since we don't know beforehand in which beats lyrics are sung, we can start with an empty dictionary. In this dictionary, the keys will be the beat numbers where a lyric is sung, and the values the occurrences of a lyric being sung in that beat.

⇒ **Note**: To print the results ordered, we can first order the keys of the dictionary with the `sorted()` function. This function returns a list, that we can save in a new variable. This variable will then contain a list with the ordered keys of our dictionary. Then, we can iterate over the list in this new variable, and call the values from the dictionary using the items of the list as keys.

In [66]:
# This cell uses the nn_vocal previously defined

# Create empty dictionary
lyrics_beats = {}

# Iterate over all notes
for n in nn_vocal:
    # Check that the note has a lyric:
    if n.lyric != None:
        # Retrieve the beat
        nb = n.beat
        # Check if that beat is NOT yet a key in the lyrics_beats dictionary
        if nb not in lyrics_beats.keys():
            # Create a new key for the current beat and assign the value of 1
            lyrics_beats[nb] = 1
        else:
            # Update the value of the current beat by 1
            lyrics_beats[nb] += 1

# Print the dictionary to check the results
print(lyrics_beats)

print()

# Let's print the ordered results
## Create a list with the sorted keys
ordered_keys = sorted(lyrics_beats.keys())

## Iterate over the ordered keys and use them to call the values in the dictionary
for k in ordered_keys:
    print('- Beat {}: lyrics were sung {} times'.format(k, lyrics_beats[k]))

{3.0: 35, 4.0: 16, 2.0: 21, 1.0: 31, 3.5: 4, 4.5: 4, 4.75: 1, 2.75: 1, 2.5: 2, 1.5: 3}

- Beat 1.0: lyrics were sung 31 times
- Beat 1.5: lyrics were sung 3 times
- Beat 2.0: lyrics were sung 21 times
- Beat 2.5: lyrics were sung 2 times
- Beat 2.75: lyrics were sung 1 times
- Beat 3.0: lyrics were sung 35 times
- Beat 3.5: lyrics were sung 4 times
- Beat 4.0: lyrics were sung 16 times
- Beat 4.5: lyrics were sung 4 times
- Beat 4.75: lyrics were sung 1 times


### 2.5. Challenge!
We want to work with pitch predominance, and we want to compare the meaning of counting notes or computing aggregated duration. Therefore, we will create a dictionary for that. The keys of this dictionary will be the pitch classes that we find in the vocal part. And the value for each key will be another dictionary. This dictionaries assigned to each pitch class will have only two items. The first one will have the key `'notes'` and its value will be the count of notes with the corresponding pitch class. The second one will have the key `'dur'` (for duration) and its value will be the aggretated duration for that pitch class. Therefore, the result of this code has two, let's say, "levels" of dictionaries: one general dictionary whose keys are the pitch classes, and then many, let's call it, "pitch dictionaries", in the amount of one per pitch class. The "pitch dictionaries" have two items, one with the key `'notes'` and one with the key `'dur'`.

Expected result:

    {'G#': {'notes': 87, 'dur': 48.25}, 'B': {'notes': 65, 'dur': 39.25}, 'F#': {'notes': 89, 'dur': 45.75}, 'E': {'notes': 70, 'dur': 40.75}, 'C#': {'notes': 63, 'dur': 37.75}, 'D#': {'notes': 25, 'dur': 12.5}, 'A': {'notes': 5, 'dur': 3.5}}

    G# is sung in 87 notes, with an aggregated duration of 48.25 quarter notes.
    F# is sung in 89 notes, with an aggregated duration of 45.75 quarter notes.

In [69]:
# This cell uses the nn_vocal previously defined

# Create the general dictionary (empty)
pitch_predominance = {}

# Iterate over all notes
for n in nn_vocal:
    # Retrieve pitch and duration
    np = n.name
    ndur = n.quarterLength
    # Check if the pitch of the current note is NOT yet among the keys of the general dictionary
    if np not in pitch_predominance.keys():
        # Create a new key for the pitch of the current note with the value of a "pitch dictionary"
        # To initiate the "pitch dictionary", give the 'notes' key the value of one,
        # and give the key 'dur' the value of the duration of the current note
        pitch_predominance[np] = {'notes': 1, 'dur': ndur}
    else:
        # The pitch of the current note is already among the keys of the general dictionary
        # Update its "note dictionary", by adding one to the value of 'notes',
        # and adding the duration of the current note to the value of 'dur'
        pitch_predominance[np]['notes'] += 1
        pitch_predominance[np]['dur'] += ndur

# Print the resulting dictionary
print(pitch_predominance)

print()

# Now you can use some information:
print('G# is sung in {} notes, with an aggregated duration of {} quarter notes.'.format(pitch_predominance['G#']['notes'], pitch_predominance['G#']['dur']))
print('F# is sung in {} notes, with an aggregated duration of {} quarter notes.'.format(pitch_predominance['F#']['notes'], pitch_predominance['F#']['dur']))

{'G#': {'notes': 87, 'dur': 48.25}, 'B': {'notes': 65, 'dur': 39.25}, 'F#': {'notes': 89, 'dur': 45.75}, 'E': {'notes': 70, 'dur': 40.75}, 'C#': {'notes': 63, 'dur': 37.75}, 'D#': {'notes': 25, 'dur': 12.5}, 'A': {'notes': 5, 'dur': 3.5}}

G# is sung in 87 notes, with an aggregated duration of 48.25 quarter notes.
F# is sung in 89 notes, with an aggregated duration of 45.75 quarter notes.


## Exercise 3. Write your own code!

### 3.1
Write a dictionary with the data for the following dog:

- name: Linda
- bride: labrador
- age: 8
- color: black
- weight: 35.2
- sex: female
- toys: ball, bone, stuffed squirrel, plastic bottle
- vaccined: false

Print the dictionary, and build a sentence describing the dog using information from the dictionary.

Expected result:

    {'name': 'Linda', 'bride': 'labrador', 'age': 8, 'color': 'black', 'weight': 35.2, 'sex': 'female', 'toys': ['ball', 'bone', 'stuffed squirrel', 'plastic bottle'], 'vaccined': False}

    Linda is a black labrador of 8 years old and 35.2 kg.

In [71]:
# Create the dictionary
dog = {'name': 'Linda', 'bride': 'labrador', 'age': 8, 'color': 'black', 'weight': 35.2, 'sex': 'female', 'toys':['ball', 'bone', 'stuffed squirrel', 'plastic bottle'], 'vaccined': False}

# Print the ditionary
print(dog)

# Print an empty line for better legibility
print()

# Print a sentece about the dog
print("{} is a {} {} of {} years old and {} kg.".format(dog['name'],dog ['color'], dog['bride'], dog['age'], dog['weight']))

{'name': 'Linda', 'bride': 'labrador', 'age': 8, 'color': 'black', 'weight': 35.2, 'sex': 'female', 'toys': ['ball', 'bone', 'stuffed squirrel', 'plastic bottle'], 'vaccined': False}

Linda is a black labrador of 8 years old and 35.2 kg.


### 3.2
Two years later, our lovely Linda has gained 2.7 kg., is totally vaccined, stopped playing with the plastic bottle, and now her favorites toys are a squeaky chicken and a knotted rope. Update the dictionary from exercise 3.1 with the new information, print it out and print the same presentation line from exercise 3.1.

Expected result:

    {'name': 'Linda', 'bride': 'labrador', 'age': 10, 'color': 'black', 'weight': 37.900000000000006, 'sex': 'female', 'toys': ['ball', 'bone', 'stuffed squirrel', 'squeaky chicken', 'knotted rope'], 'vaccined': True}

    Linda is a black labrador of 10 years old and 37.900000000000006 kg.
    
⇒ **Note**: remember the problems with floating points. For the updated weight, you might get different decimals.

In [83]:
# This cell requires the dictionary created in exercise 3.1

# Update the different items

dog['age'] += 2
dog['weight'] += 2.7
dog['vaccined'] = True
dog['toys'].append('squeaky chicken') 
dog['toys'].append('knotted rope')
dog['toys'].remove('plastic bottle')

# Print the ditionary

print(dog)
# Print an empty line for better legibility
print()

# Print a sentece about the dog
print("{} is a {} {} of {} years old and {} kg.".format(dog['name'], dog['color'], dog['bride'], dog['age'], dog['weight']))

{'name': 'Linda', 'bride': 'labrador', 'age': 10, 'color': 'black', 'weight': 37.900000000000006, 'sex': 'female', 'toys': ['ball', 'bone', 'stuffed squirrel', 'squeaky chicken', 'knotted rope'], 'vaccined': True}

Linda is a black labrador of 10 years old and 37.900000000000006 kg.


### 3.3
How many measures start with a tied note in the vocal part?

Expected result:

    The vocal part has 5 measures which start with a tied note.

⇒ *Hint*: to do this, you can search for notes in beat 1 which have a tie of the type `stop` or `continue`.

In [89]:
# This cell uses the nn_vocal previously defined

# Initiate a counter
ties = 0

# Iterate over all notes. Check if their beat is 1. If so, check if they have a tie, and
# if the tie is of the type stop or continue. If so, update the counter
for n in nn_vocal:
    if n.beat == 1:
        if n.tie and (n.tie.type == 'stop' or n.tie.type == 'continue'):
            ties += 1
            
# Print results
print("The voal part has {} measures which start with a tied note.".format(ties))


The voal part has 5 measures which start with a tied note.


### 3.4
Check how many notes with lyrics in the vocal part are preceded by a grace note.

Expected result:

    In the vocal part, 15 notes with lyrics are preceded by a grace note.

⇒ *Hint*: since you need to find a note with lyrics and then check the previous note to that one, you better iterate over the notes using idexing. And do not start the iteration with the first note, for the following reasons of logic: if it is the first note, it cannot be preceded by any note, and if you compute the index before the first one, that is, the one before index `0`, you will be using index `-1`, so you will retrieve the last note! Therefore, start your iteration from index `1`.

In [91]:
# This cell uses the nn_vocal previously defined

# Initiate a counter
grace_notes = 0

# Iterate over the indexes of the ntoes starting from the second one. Then check if the note
# in the current index has a lyric. If so, check if the note in previous index is a grace
# note. And if it is a grace note, update the counter.


for i in range(1, len(nn_vocal)):
    note = nn_vocal[i]
    if note.lyric != None:
        pre_note = nn_vocal[i-1]
        if pre_note.quarterLength == 0:
            grace_notes += 1

# Print the results
print("In the vocal part, {} notes with lyrics are preceded by a grace note.".format(grace_notes))

In the vocal part, 15 notes with lyrics are preceded by a grace note.


⇒ **Optional**: can you compute which percentage of the total number of notes with lyrics are preceded by a grace note?

### 3.5
Are there preferred pitches for singing lyrics? Create a dictionary whose keys are the pitches found in the vocal part and their values the number of times that those pitches are sung with a lyric. Then print the dictionary and the results for the first degree of the scale (E) and the for the 4th and 7th degrees (A and D#).

Expected result:

    {'G#': 25, 'B': 23, 'E': 24, 'F#': 18, 'C#': 17, 'D#': 7, 'A': 4}

    Lyrics are sung in E in 24 occasions.
    Lyrics are sung in A in 4 occasions.
    Lyrics are sung in D# in 7 occasions.

In [93]:
# This cell uses the nn_vocal previously defined

# Create an empty dictionary
pitches = {}

# Iterate over all notes. Retrieve pitch. Check if it contains a lyric. If so,
# check if the pitch is NOT yet among the dictionary keys. If so, add the pitch
# of the current note as key with the initial value of 1. If it is already among
# the keys of the dictionary, update its value by 1.

for n in nn_vocal:
    n_pitch = n.name
    if n.lyric != None:
        if n_pitch not in pitches.keys():
            pitches[n_pitch] = 1
        else:
            pitches[n_pitch] += 1



# Print the ditionary
print(pitches)

# Print an empty line for better legibility
print()

# Print results for E, A and D#

print("Lyrics are sung in E in {} occasions.".format(pitches['E']))
print("Lyrics are sung in A in {} occasions.".format(pitches['A']))
print("Lyrics are sung in D# in {} occasions.".format(pitches['D#']))


{'G#': 25, 'B': 23, 'E': 24, 'F#': 18, 'C#': 17, 'D#': 7, 'A': 4}

Lyrics are sung in E in 24 occasions.
Lyrics are sung in A in 4 occasions.
Lyrics are sung in D# in 7 occasions.
